### ISSUE TITLE
No  'Xtensions' from SPM.

### ISSUE THREAD

**Issue by pujiaxin33** [nunogoncalves/iOS-OctoPodium#21]
I can't download 'Xtensions' from SPM. Is there something wrong?

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/82997393-e6dbd200-a038-11ea-8f3c-04b9b682ab0f.png)

**Comment by nunogoncalves** [comment]
Ahhhhh... totally forgot this. Xtensions is a private repo. I guess I’ll have to make it public.

**Comment by nunogoncalves** [comment]
You can try again. :)

**Comment by nunogoncalves** [comment]
By the way. Nuke should not be an issue. It’s an open source repo..

**Comment by pujiaxin33** [comment]
Thank you! It's perfect!
