### ISSUE TITLE
Small readme typo

### ISSUE THREAD

**Issue by andrejewski** [nunogoncalves/iOS-OctoPodium#3]
<img width="919" alt="screen shot 2016-03-12 at 9 14 52 am" src="https://cloud.githubusercontent.com/assets/1660953/13723434/39525c4c-e833-11e5-995d-a7bc29a04e58.png">

Sorry to bother about something so trivial, but it was the first thing I noticed on the project page and is worth correcting.

**Comment by nunogoncalves** [comment]
Damn! :D never noticed that! :) thanks.

**Comment by nunogoncalves** [comment]
Fixed. :) Thanks again @andrejewski
