### ISSUE TITLE
I getting error when run 

### ISSUE THREAD

**Issue by kcaglarr** [nunogoncalves/iOS-OctoPodium#5]
error: reading data: The file “Github.plist” couldn’t be opened because there is no such file.

**Comment by nunogoncalves** [comment]
Hi,

That's actually a requirement that is specified in the Read me. The github and google plist files contain personal information. You should create your own ones to test the app locally.

**Comment by kcaglarr** [comment]
Sorry,I missed it

**Comment by nunogoncalves** [comment]
Actually I could try to make them not necessary for testing purposes. Use them if available, otherwise block the features that rely on them. :)

Closing this for now. And thanks.
